name: your_book_of_friends
description: A management tool for relationships with your friends.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-30.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  sqflite: ^2.1.0
  sqlite3_flutter_libs: ^0.5.10
  path_provider: ^2.0.0
  path: ^1.8.2
  google_fonts: ^3.0.1
  provider: ^6.0.3
  collection: ^1.16.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true